# Muxiveo — correctif ncnn (idempotent) : active VK_KHR_external_memory_fd / _win32 quand le GPU les propose,
# pour partager des tampons Vulkan avec CUDA (plugin TensorRT de muxiveo-rife). Aucun effet sans plugin.
function(muxiveo_patch_ncnn ncnn_dir)
    set(target "${ncnn_dir}/src/gpu.cpp")
    file(READ "${target}" content)
    string(FIND "${content}" "MUXIVEO_EXTERNAL_MEMORY_EXPORT" marker)
    if(marker GREATER -1)
        return()
    endif()
    set(anchor "        enabledExtensions.push_back(\"VK_KHR_external_memory\");\n")
    string(FIND "${content}" "${anchor}" position)
    if(position EQUAL -1)
        message(FATAL_ERROR "Correctif ncnn : ancre VK_KHR_external_memory introuvable dans ${target} (ncnn modifié ?)")
    endif()
    file(READ "${CMAKE_CURRENT_LIST_DIR}/cmake/ncnn_external_memory.inc" addition)
    string(REPLACE "${anchor}" "${anchor}${addition}" content "${content}")
    file(WRITE "${target}" "${content}")
    message(STATUS "ncnn : export de mémoire Vulkan activé (correctif muxiveo-rife)")
endfunction()
